pipeline {
    agent any
    environment {
        WEBSERVER = "54.234.22.220"
    }
    stages {
        stage("source checkout") {
            steps {
                git 'https://github.com/madhukummari/CICD.git' // Clones the whole repo
            }
        }

        stage('install dependencies') {
            steps {
                dir('adoc/frontend') { // Navigate to frontend folder
                    sh 'npm install'
                }
            }
        }

        stage('build react app') {
            steps {
                dir('adoc/frontend') { // Navigate to frontend folder
                    sh 'npm run build'
                }
            }
        }

        stage('deploy to nginx') {
            steps {
                sshagent(['jenkins-ssh-key']) {
                    sh 'scp -r adoc/frontend/build/* ubuntu@${WEBSERVER}:/var/www/react-app/'
                }
            }
        }

        stage('restart nginx') {
            steps {
                sshagent(['jenkins-ssh-key']) {
                    sh 'ssh ubuntu@${WEBSERVER} "sudo systemctl restart nginx"'
                }
            }
        }
    }
}
